In [1]:
!pip install numpy

  Using cached numpy-1.26.4-cp311-cp311-macosx_11_0_arm64.whl.metadata (114 kB)
Using cached numpy-1.26.4-cp311-cp311-macosx_11_0_arm64.whl (14.0 MB)


In [2]:
import numpy as np

In [36]:
b = 0.8 # probability of not jumping
n = 4 # number of nodes
transitionMatrix = np.array([
    [0, 1/2, 0, 0], 
    [1/3, 0, 0, 1/2], 
    [1/3, 0, 1, 1/2], 
    [1/3, 1/2, 0, 0]])
vInitial = np.array([1/n, 1/n, 1/n, 1/n]) # initial distribution

In [25]:
v = vInitial
tolerance = 1e-6
converged = False
numOfIterations = 0
while not converged:
    numOfIterations += 1
    newV = b * np.dot(transitionMatrix, v) + (1 - b) / n
    if np.allclose(newV, v, atol=tolerance):
        converged = True
    v = newV
print(v, numOfIterations)

[0.10135339 0.12838135 0.64188392 0.12838135] 20


In [31]:
v = vInitial
# closed form
ans = np.dot((np.identity(4) - np.dot(v, transitionMatrix))**-1, 1-b)
print(ans)

[[ 0.26666667 -0.8        -0.8        -0.8       ]
 [-0.8         0.26666667 -0.8        -0.8       ]
 [-0.8        -0.8         0.26666667 -0.8       ]
 [-0.8        -0.8        -0.8         0.26666667]]


In [45]:
# closed form calculation for the page rank algorithm of modified version of pagerank
v = vInitial
ans = np.linalg.inv(np.identity(4) - b * transitionMatrix) * (1 - b)
result = np.dot(ans, v)
print(result)

[0.10135135 0.12837838 0.64189189 0.12837838]


In [26]:
print(sum(v))

0.9999999999999998


In [7]:
print(15/148, 19/148, 95/148, 19/148)

0.10135135135135136 0.12837837837837837 0.6418918918918919 0.12837837837837837


In [ ]:
b = 0.8 # probability of not jumping
n = 4 # number of nodes

# Generate matrix
transitionMatrix = np.array([
    [0, 1/2, 0, 0], 
    [1/3, 0, 0, 1/2], 
    [1/3, 0, 1, 1/2], 
    [1/3, 1/2, 0, 0]])

# TODO: how to determine initial distribution?
vInitial = np.array([1/n, 1/n, 1/n, 1/n]) # initial distribution